Ejercicios Temas 1, 2 ,3 Diego Fernando Galeano Duran
UnirDwfs/DWFS-PER7610-2223 pull request #104
Opened 2022-12-08 17:09 UTC by diego-fernando-galeano

2022-12-09 08:50 UTC, UnirDwfs requested changes
Los archivos del ejercicio del tema 5 deben estar en la carpeta correcta.
Lo demás OK

2022-12-09 08:50 UTC, UnirDwfs commented on Tema_3/Diego Fernando Galeano Duran/E1/T3_E1.js
> +    if(dniLetterPosition<letras.length){
No es necesaria esta comprobación dada la definición matemática de resto

2022-12-09 08:50 UTC, UnirDwfs commented on Tema_5/Diego Fernando Galeano Duran/users-app/src/App.js
> +import './App.css';
Este archivo y su hoja de estilos va dentro de /components y /styles respectivamente.

2022-12-10 22:37 UTC, diego-fernando-galeano commented
Cordial saludo,

Se han realizado los cambios solicitados.

Agradezco sus observaciones.

2022-12-11 12:07 UTC, UnirDwfs approved these changes

2022-12-11 12:07 UTC, merged