chuck norris facts js html css
UnirDwfs/DWFS-PER7610-2223 pull request #86
Opened 2022-11-29 15:06 UTC by GuillermoLopezPazos1

usando consumo de api mediante fetch para cambiar el valor de un parrafo

2022-11-29 15:35 UTC, UnirDwfs commented on Tema_4/guillermo-lopez/ejercicio1.html
> +<!DOCTYPE html>
Mueve ambos archivos dentro del Tema 3 por favor!

2022-11-29 15:35 UTC, UnirDwfs requested changes
Mueve ambos archivos dentro del Tema 3 por favor!

2022-11-29 19:02 UTC, GuillermoLopezPazos1 commented on Tema_4/guillermo-lopez/ejercicio1.html
> +<!DOCTYPE html>
con una nueva pull request? los tengo ya reordenados en mi repo

2022-11-30 16:23 UTC, UnirDwfs commented on Tema_4/guillermo-lopez/ejercicio1.html
> +<!DOCTYPE html>
entonces simplemente haz push y debería actualizarse esta pr, si ves que no es así abre una nueva sin problema

2022-11-30 16:24 UTC, UnirDwfs approved these changes
se ha cambiado con tu push automaticamente, ok!

2022-11-30 16:24 UTC, merged