Ejercicios 1, 2, 3, 4
UnirDwfs/DWFS-PER7610-2223 pull request #92
Opened 2022-11-30 19:43 UTC by arnoboas

2022-12-01 09:08 UTC, UnirDwfs commented on Tema_2/AlexisNoboa/cinema.js
> +function suggest(requestSize) {
Deberías refactorizar este método, debería ser más sencillo

2022-12-01 09:16 UTC, UnirDwfs requested changes
Revisa todos los comentarios que he dejado Alexis. En general hay que mejorar bastantes cosas.

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_2/AlexisNoboa/cinema.js
> +//let suggestion2 = suggest(8);//let suggestion3 = suggest(11);
¿Por que comentas el programa principal? :O

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_2/AlexisNoboa/cinema.js
> +function order(requestSize) {
order tiene que invocar si o sí a suggest, esto está mal.

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_2/AlexisNoboa/cinema.js
> +var size=4;
size, asientosRequeridos... se pasa por parametro en el programa principal, no con el readLine. Tampoco es para nada correcto que sean variables declaradas con 'var'.
La única 'var' debería ser aquella que contenga el estado de la sala.

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_2/AlexisNoboa/cinema.js
> +    for (let i = 0; i < size; i++) {
No tiene ningún sentido conforme a lo pedido

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_3/AlexisNoboa/T3_E1.js
> +        for(let i=0;i<letras.length;i++){
¿por qué recorres el array? puedes hacer directamente letras[resto] ya que resto tomará valores entre 0 y 22 siempre, por la propia definición matemática de resto.

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_3/AlexisNoboa/T3_E2.js
> +    arreglo=arreglo.map(valor=>valor*2);
puedes combinar ambas sentencias

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_3/AlexisNoboa/T3_E2.js
> + function media(arreglo){
OK, aunque lo que se quería es que usases reduce()

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_3/AlexisNoboa/T3_E2.js
> +
Tienes que formatear mucho mejor tu código... ¿todas estas líneas en blanco qué objeto tienen?

2022-12-01 09:16 UTC, UnirDwfs commented on Tema_4/Alexis Noboa E4/APIChukNorris.html
> +<!DOCTYPE html>
Este ejercicio tiene que estar dentro de la carpeta del tema 3.
Si no, no se puede mergear.

2022-12-08 00:46 UTC, arnoboas commented on Tema_2/AlexisNoboa/cinema.js
> +    for (let i = 0; i < size; i++) {
Los asientos sugeridos entendí que dependen de lo que el cliente pida, por ejemplo si el cliente quiere ordenar 4 entradas , entonces primero se tiene que sugerir 4 puestos y posterior el cliente acepta o no y el decide los asientos que quiere, o como sería de sugerir los puestos de acuerdo a que parámetro?

2022-12-08 00:47 UTC, arnoboas commented on Tema_2/AlexisNoboa/cinema.js
> +function suggest(requestSize) {
Yo le hice que sugiera primero desde las filas de la mitad de la sala de cine porque es lo que normalmente la gente pide cuando ordena entradas, que se encuentre en la mitad de la sala de forma horizontal y vertical.

2022-12-08 00:49 UTC, arnoboas commented on Tema_2/AlexisNoboa/cinema.js
> +function order(requestSize) {
Entendí que primero se ordena una cantidad de asientos, posteriormente se sugiere los asientos de acuerdo al número de asientos que se pidió, luego el cliente acepta o rechaza la sugerencia y si rechaza la sugerencia , el cliente decide que asientos quiere ordenar

2022-12-08 00:53 UTC, arnoboas commented on Tema_3/AlexisNoboa/T3_E2.js
> +
Entonces debería escribir el código sin líneas en blanco? , normalmente lo hago para que se entienda mejor el código.

2022-12-08 01:13 UTC, arnoboas commented on Tema_3/AlexisNoboa/T3_E2.js
> + function media(arreglo){
ok

2022-12-08 01:14 UTC, arnoboas commented on Tema_3/AlexisNoboa/T3_E2.js
> +
Se puede poner líneas en blanco en algún caso o el código debería ir todo seguido sin ninguna línea en blanco?

2022-12-08 09:56 UTC, UnirDwfs approved these changes

2022-12-08 09:57 UTC, merged